import os
from dataclasses import dataclass

@dataclass
class Config:
    ASTERISK_HOST = os.getenv('ASTERISK_HOST', '127.0.0.1')
    """ The host of the asterisk server """
    ASTERISK_AMI_PORT = os.getenv('ASTERISK_AMI_PORT', '5038')
    """ The port where asterisk is listening for AMI commands. Default is 5038 """
    ASTERISK_AMI_USER = os.getenv('ASTERISK_AMI_USER', 'asteramisk')
    """ The username to use when connecting to Asterisk Manager Interface. This needs to be configured in manager.conf on the asterisk server """
    ASTERISK_AMI_PASS = os.getenv('ASTERISK_AMI_PASS', 'asteramisk')
    """ The password to use when connecting to Asterisk Manager Interface. This needs to be configured in manager.conf on the asterisk server """
    ASTERISK_INCOMING_CALL_CONTEXT = os.getenv('ASTERISK_INCOMING_CALL_CONTEXT', 'asteramisk-incoming-call')
    """ The context to which your Asterisk PSTN endpoint will send incoming calls. This is the context=your_context line in pjsip.conf under your PSTN endpoint configuration """
    ASTERISK_INCOMING_TEXT_CONTEXT = os.getenv('ASTERISK_INCOMING_TEXT_CONTEXT', 'asteramisk-incoming-text')
    """ The context to which your Asterisk PSTN endpoint will send incoming text messages. This is the message_context=your_context line in pjsip.conf under your PSTN endpoint configuration """
    ASTERISK_PSTN_ENDPOINT = os.getenv('ASTERISK_PSTN_ENDPOINT', 'pstn_endpoint')
    """ The name of your PSTN endpoint as configured in pjsip.conf """
    ASTERISK_PSTN_GATEWAY_HOST = os.getenv('ASTERISK_PSTN_GATEWAY_HOST', 'toronto1.voip.ms')
    """ The host of your PSTN gateway as configured in pjsip.conf """
    ASTERISK_PSTN_GATEWAY_PORT = os.getenv('ASTERISK_PSTN_GATEWAY_PORT', '5060')
    """ The port of your PSTN gateway as configured in pjsip.conf. Default is 5060, which is nearly always correct """
    ASTERISK_PSTN_GATEWAY_USER = os.getenv('ASTERISK_PSTN_GATEWAY_USER', 'asteramisk')
    """ The username to use when connecting to your PSTN gateway. This is the value of the username line in pjsip.conf under your PSTN auth configuration """
    
    ASTERISK_SOUNDS_DIR = os.getenv('ASTERISK_SOUNDS_DIR', '/usr/share/asterisk/sounds')
    """ The directory where asterisk stores sound files. Default is /usr/share/asterisk/sounds """
    ASTERISK_TTS_SOUNDS_SUBDIR = os.getenv('ASTERISK_SOUNDS_SUBDIR', 'asteramisk')
    """ The subdirectory where asterisk stores audio files that are generated by asteramisk for text to speech. Default is asteramisk """

    AGI_SERVER_HOST = os.getenv('AGI_SERVER_HOST', '127.0.0.1')
    """ The host of the asterisk AGI server. Default is 127.0.0.1 """
    AGI_SERVER_PORT = os.getenv('AGI_SERVER_PORT', '4573')
    """ The port to use for the asterisk AGI server. Default is 4573. Does not need to be configured anywhere else """

    SYSTEM_PHONE_NUMBER = os.getenv('SYSTEM_PHONE_NUMBER')
    """ The phone number associated with your telephony system. Used as the caller ID when making outgoing calls, if not specified in your code. """
    SYSTEM_NAME = os.getenv('SYSTEM_NAME', 'Default')
    """ The name of your system. Used as the caller ID name when making outgoing calls, if not specified in your code. """
    SYSTEM_VOICE = os.getenv('SYSTEM_VOICE', 'en-US-Neural2-J')
    """ The voice to use when speaking to the user. Default is en-US-Neural2-J. See https://cloud.google.com/text-to-speech/docs/voices for all available voices """

    GOOGLE_APPLICATION_CREDENTIALS = os.getenv('GOOGLE_APPLICATION_CREDENTIALS')
    """ The path to the google application credentials file. This is needed for the google cloud speech api. Without it, this library is very limited. """

config = Config()

# Set environment variable GOOGLE_APPLICATION_CREDENTIALS
# This is needed for the google cloud speech api
# I don't get why they make this so complicated by needing to set an environment variable
if config.GOOGLE_APPLICATION_CREDENTIALS is not None:
    os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = config.GOOGLE_APPLICATION_CREDENTIALS
